version: "3.3"

services:
  tribler-core:
    image: triblercore/triblercore:latest
    container_name: triblercore
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.debian
    volumes:
      - ~/.Tribler:/home/user/.Tribler
    environment:
      CORE_API_PORT: 20100
      CORE_API_KEY: TEST
      #TSTATEDIR: TEST
    ports:
      - "20100:20100"
